apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: aci-apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/m-gran/devsecops-manifests.git
      revision: HEAD
      directories:
      - path: networking/aci/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: aci-project
      source:
        repoURL: https://github.com/m-gran/devsecops-manifests.git
        targetRevision: HEAD
        path: '{{path}}/base'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  
        retry:
          limit: 10
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m

