apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-team-a
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/m-gran/devsecops-manifests.git
        revision: HEAD
        directories:
          # Explicitly list the app directories you want to search
          - path: apps/dev-team-a/devsecops-demo-app/overlays/dev
          - path: apps/dev-team-a/devsecops-demo-app/overlays/prod
  template:
    metadata:
      # .path.segments 2 = "devsecops-demo-app"
      # .path.segments 4 = "dev" or "prod"
      name: '{{index .path.segments 2}}-{{index .path.segments 4}}'
    spec:
      project: dev-team-a-project
      source:
        repoURL: https://github.com/m-gran/devsecops-manifests.git
        targetRevision: HEAD
        # We manually append the overlay path to the discovered directory
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'dev-team-a-{{index .path.segments 4}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true