apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-team-a-preview
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - matrix: # This is the missing link to combine both generators
        generators:
          - pullRequest:
              github:
                owner: m-gran
                repo: devsecops-manifests
                tokenRef:
                  secretName: dev-team-a-github-token
                  key: token
                labels:
                  - preview
              requeueAfterSeconds: 1800
          - git:
              repoURL: https://github.com/m-gran/devsecops-manifests.git
              revision: HEAD
              directories:
                - path: apps/dev-team-a/devsecops-demo-app/overlays/dev
  template:
    metadata:
      name: '{{.path.basename}}-pr-{{.number}}'
    spec:
      project: dev-team-a-project
      source:
        repoURL: https://github.com/m-gran/devsecops-manifests.git
        targetRevision: '{{.head_sha}}'
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev-team-a-dev 
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true