apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-team-a
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/m-gran/devsecops-manifests.git
      revision: HEAD
      directories:
      - path: apps/dev-team-a/*
  template:
    metadata:
      name: '{{path.basename}}-dev'
    spec:
      project: dev-team-a-project
      source:
        repoURL: https://github.com/m-gran/devsecops-manifests.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev-team-a-dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
