apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-team-a
  namespace: argocd
spec:
  generators:
  # Generate applications for each PR
  - pullRequest:
      github:
        owner: m-gran
        repo: devsecops-manifests
        labels:
        - preview
      requeueAfterSeconds: 1800
  # Generate applications for each environment
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/m-gran/devsecops-manifests.git
          revision: HEAD
          directories:
          - path: apps/dev-team-a/*
      - list:
          elements:
          - env: dev
          - env: prod
  template:
    metadata:
      name: '{{path.basename}}-{{env}}'
    spec:
      project: dev-team-a-project
      source:
        repoURL: https://github.com/m-gran/devsecops-manifests.git
        targetRevision: HEAD
        path: '{{path}}/overlays/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev-team-a-{{env}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
