apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: namespace-policy-exception
  namespace: kyverno # Typically created in the Kyverno namespace
spec:
  exceptions:
  - policyName: require-labels
    ruleNames:
    - "*"
  match:
    any:
    - resources:
        namespaces:
        - crossplane-system
        - kyverno