apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: namespace-policy-exception
  namespace: kyverno
spec:
  exceptions:
  - policyName: require-labels
    ruleNames:
    - "*"
  match:
    any:
    - resources:
        namespaces:
        - crossplane-system
        - kyverno
        kinds:
        - "*" # Ensure it catches all resource types in those namespaces