apiVersion: policies.kyverno.io/v1
kind: ValidatingPolicy
metadata:
  name: require-probes
  annotations:
    policies.kyverno.io/title: Require Probes
    policies.kyverno.io/category: Best Practices
spec:
  validationFailureAction: Enforce
  matchConstraints:
    resourceRules:
      - apiGroups: ["apps"]
        apiVersions: ["v1"]
        kinds: ["Deployment", "StatefulSet", "DaemonSet"]
        operations: ["CREATE", "UPDATE"]
  validatingAdmissionPolicy:
    variables:
      # Extract the list of containers from the workload template
      - name: containers
        expression: "object.spec.template.spec.containers"
    validations:
      - expression: "variables.containers.all(c, has(c.livenessProbe) && has(c.readinessProbe))"
        message: "Liveness and Readiness probes are required for all containers."