---
apiVersion: v1
kind: Service
metadata:
  name: demo-app-devsecops-lab-lb
  annotations:
    # Provisions a Network Load Balancer (NLB) instead of a Classic Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # Ensures the NLB is internal and gets private IPs from the EKS VPC (10.0.0.0/16)
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: devsecops-lab-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80